# -*- coding: utf-8 -*-
"""Sajid_my_EEG_project_updated.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aYEOAdu1Uz0nYa3xJbpEppwvqI1gsTpr

# **All preprocessing of data before training ML and DL models**

# First I will import the libraries and do preprocessing so that the data will be used for training ML/DL models
- Each type of model requires different type of data i.e one type for ML and one type DL
"""

# ============================================
# 1. IMPORT LIBRARIES - for preprocessing before ML n DL
# ============================================
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns
from lightgbm import LGBMClassifier

# ============================================
# 2. MOUNT GOOGLE DRIVE - as our data is stored in G-drive
# ============================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================
# 3. DEFINE FILE PATHS & LABELS - to mention the files located
# ============================================

data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG"

# Map each file to its label
file_label_map = {
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow_movement",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "listening_music",
    "Sub1Relax.csv": "relaxed_closed",
    "Sub1Relaxopen.csv": "relaxed_open",
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking"
}

# ============================================
# 4. LOAD & MERGE ALL FILES - we need to merge
# ============================================
dataframes = []

for file, label in file_label_map.items():
    df = pd.read_csv(os.path.join(data_path, file))
    df["label"] = label
    dataframes.append(df)

# Merge all - we will use concat to merging all
df_all = pd.concat(dataframes, ignore_index=True)

print("Merged shape:", df_all.shape)
print(df_all["label"].value_counts())

"""To check for class imbalance"""

import matplotlib.pyplot as plt

# Count labels
label_counts = df_all["label"].value_counts()

# Create bar plot
plt.figure(figsize=(12, 6))
label_counts.plot(kind='bar')

# Labels and title
plt.xlabel("Activity Labels")
plt.ylabel("Number of Samples")
plt.title("Class Distribution of EEG Activity Dataset")

# Rotate labels for readability
plt.xticks(rotation=45, ha='right')

# Show grid for better analysis
plt.grid(axis='y')

plt.tight_layout()
plt.show()

# ============================================
# 6. SAVE MERGED DATASET AS CSV - one giant combined file
# ============================================

# Define output path (change folder name if needed)
output_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG/merged_EEG_dataset.csv"

# Save to CSV
df_all.to_csv(output_path, index=False)

print("Merged dataset saved successfully at:")
print(output_path)

# ============================================
# 5. HANDLE MISSING VALUES- if we find some missing values
# ============================================
df_all.fillna(method='ffill', inplace=True)

# ============================================
# 6. NORMALIZATION - we need to normalization on all features
# ============================================
features = df_all.drop("label", axis=1)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

df_scaled = pd.DataFrame(scaled_features, columns=features.columns)
df_scaled["label"] = df_all["label"].values

print(df_scaled.head())

# ============================================
# 7. EDA (quick visualization)
# ============================================
plt.figure(figsize=(10,4))
plt.plot(df_scaled["EEG.AF3"][:500])
plt.title("Sample EEG Signal (AF3)")
plt.show()

# ============================================
# 8. WINDOWING FUNCTION - we need to create windows for experiments
# ============================================
def create_windows(data, labels, window_size, step_size):
    X = []
    y = []

    for i in range(0, len(data) - window_size, step_size):
        X.append(data[i:i+window_size])
        y.append(labels[i])

    return np.array(X), np.array(y)

# Parameters
window_size = 128   # i will try 128, 256 later
step_size = 64      # overlap

# Apply windowing
X, y = create_windows(
    df_scaled.drop("label", axis=1).values,
    df_scaled["label"].values,
    window_size,
    step_size
)

print("Windowed data shape:", X.shape)

"""# **ML model on EEG+motion sensor data i.e including motion artifact sensor data i.e using all features**"""

# ============================================
# 9. LABEL ENCODING - as y features - need to be converted into 12 categories 0-11
# ============================================
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# ============================================
# 10. TRAIN-TEST SPLIT - before ML
# ============================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42
)

# ============================================
# 11. FLATTEN DATA FOR ML MODELS
# ============================================
# ML models need 2D input → flatten time dimension
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

print("Flattened shape:", X_train_flat.shape)

print("X_train_flat looks like", X_train_flat)
print("y_train_looks like",y_train)

# ============================================
# 12. TRAIN ML MODELS
# ============================================
#  LightGBM
lgbm = LGBMClassifier(
    n_estimators=200,
    max_depth=-1,
    learning_rate=0.1,
    random_state=42
)
lgbm.fit(X_train_flat, y_train)

# Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_flat, y_train)

# Support Vector Classifier (SVC)
from sklearn.svm import SVC
svc = SVC(kernel='rbf', C=1.0, random_state=42)
svc.fit(X_train_flat, y_train)


# ============================================
# 13. EVALUATION FUNCTION - we need to evaluate on different metrics
# ============================================
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)

    print(f"\n===== {name} Results =====")
    print("Accuracy:", accuracy_score(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    # Confusion Matrix
    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_,
                yticklabels=le.classes_)
    plt.title(f"{name} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# ============================================
# 14. EVALUATE MODELS - for all 3 models
# ============================================
evaluate_model(rf, X_test_flat, y_test, "Random Forest")
evaluate_model(svc, X_test_flat, y_test, "SVC")
evaluate_model(lgbm, X_test_flat, y_test, "LightGBM ")

"""Table: Machine Learning Model Performance (EEG Only)

Model======	Accuracy	Precision	Recall 	F1-Score

Random Forest=	0.88	0.89	0.88	0.88

SVC====	0.79	0.81	0.79	0.78

LightGBM===	0.91	0.91	0.91	0.91
"""

import matplotlib.pyplot as plt
import numpy as np

# Model names
models = ['Random Forest', 'SVC', 'LightGBM']

# Metrics
accuracy = [0.88, 0.79, 0.91]
precision = [0.89, 0.81, 0.91]
recall = [0.88, 0.79, 0.91]
f1_score = [0.88, 0.78, 0.91]

# X-axis positions
x = np.arange(len(models))
width = 0.2  # width of bars

# Plot
plt.figure(figsize=(10, 6))

plt.bar(x - 1.5*width, accuracy, width, label='Accuracy')
plt.bar(x - 0.5*width, precision, width, label='Precision')
plt.bar(x + 0.5*width, recall, width, label='Recall')
plt.bar(x + 1.5*width, f1_score, width, label='F1-Score')

# Labels and title
plt.xlabel("Models")
plt.ylabel("Scores")
plt.title("Machine Learning Model Performance (EEG Only)")
plt.xticks(x, models)
plt.ylim(0.7, 1.0)

# Legend
plt.legend()

plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""as we can see from above:

The bar chart compares the performance of classical machine learning models on EEG-only data. LightGBM demonstrates the highest performance across all evaluation metrics, followed by Random Forest, while SVC shows comparatively lower results. The consistency across accuracy, precision, recall, and F1-score indicates stable model behaviour, with LightGBM emerging as the most effective model for this task.

# **Experiments run on diff Window sizes- ML algos & comparison table**

# Here we will change the different window sizes to basically check or experiment whether it affects the accuracy of models
"""

# ============================================
# IMPORTS
# ============================================
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier

import matplotlib.pyplot as plt
import seaborn as sns

# FILE PATH
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG/"  # CHANGE THIS

# ============================================
# FILE → LABEL MAP
# ============================================
file_label_map = {
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking",
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "music",
    "Sub1Relax.csv": "relaxed_closed",
    "Sub1Relaxopen.csv": "relaxed_open"
}


# ============================================
# WINDOW FUNCTION
# ============================================
def create_windows(data, window_size, overlap):
    step = int(window_size * (1 - overlap))
    windows = []
    for i in range(0, len(data) - window_size, step):
        windows.append(data[i:i+window_size])
    return np.array(windows)

# ============================================
# BUILD DATASET (EEG + MOTION)
# ============================================
def build_dataset(window_size=128, overlap=0.5):

    X_all = []
    y_all = []

    # find common columns
    common_cols = None
    for file in file_label_map:
        df = pd.read_csv(os.path.join(data_path, file))
        cols = set(df.columns)
        if common_cols is None:
            common_cols = cols
        else:
            common_cols = common_cols.intersection(cols)

    common_cols = sorted(list(common_cols))

    # build dataset
    for file, label in file_label_map.items():
        df = pd.read_csv(os.path.join(data_path, file))
        df = df[common_cols]

        df.fillna(method='ffill', inplace=True)

        scaler = StandardScaler()
        data_scaled = scaler.fit_transform(df)

        windows = create_windows(data_scaled, window_size, overlap)

        labels = [label] * len(windows)

        X_all.append(windows)
        y_all.extend(labels)

    X_all = np.vstack(X_all)
    y_all = np.array(y_all)

    return X_all, y_all

# ============================================
# EVALUATION FUNCTION
# ============================================
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)

    print(f"\n===== {name} =====")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

# ============================================
# MODELS
# ============================================
rf = RandomForestClassifier(n_estimators=150, random_state=42)

svm = SVC(kernel='rbf', C=5, gamma='scale')


lgbm = LGBMClassifier(
    n_estimators=200,
    max_depth=-1,
    learning_rate=0.1,
    random_state=42
)

# ============================================
# WINDOW EXPERIMENT
# ============================================
window_sizes = [64, 128, 256]
overlap = 0.5

le = LabelEncoder()

for w in window_sizes:
    print(f"\n\n========= WINDOW SIZE: {w} =========")

    X, y = build_dataset(window_size=w, overlap=overlap)

    y = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # flatten for ML
    X_train_flat = X_train.reshape(X_train.shape[0], -1)
    X_test_flat = X_test.reshape(X_test.shape[0], -1)

    # train
    rf.fit(X_train_flat, y_train)
    svm.fit(X_train_flat, y_train)
    lgbm.fit(X_train_flat, y_train)

    # evaluate
    evaluate_model(rf, X_test_flat, y_test, f"RF (W={w})")
    evaluate_model(svm, X_test_flat, y_test, f"SVM (W={w})")
    evaluate_model(lgbm, X_test_flat, y_test, f"LightGBM (W={w})")

"""Performance Comparison Across Window Sizes

Window Size	Model	Accuracy	Precision (Weighted)	Recall (Weighted)	F1-Score (Weighted)

64
  Random Forest	0.845	0.85	0.84	0.84

	SVM	0.814	0.83	0.81	0.82

	LightGBM	0.907	0.91	0.91	0.91
  

128
  Random Forest	0.803	0.81	0.80	0.80

  SVM	0.635	0.64	0.63	0.63

  LightGBM	0.798	0.81	0.80	0.80

256
  Random Forest	0.657	0.67	0.66	0.66

	SVM	0.284	0.33	0.28	0.29

	LightGBM	0.569	0.58	0.57	0.57
"""

import matplotlib.pyplot as plt
import numpy as np

# Labels
labels = [
    'RF-64', 'SVM-64', 'LGBM-64',
    'RF-128', 'SVM-128', 'LGBM-128',
    'RF-256', 'SVM-256', 'LGBM-256'
]

# Metrics data
accuracy = [0.845, 0.814, 0.907, 0.803, 0.635, 0.798, 0.657, 0.284, 0.569]
precision = [0.85, 0.83, 0.91, 0.81, 0.64, 0.81, 0.67, 0.33, 0.58]
recall = [0.84, 0.81, 0.91, 0.80, 0.63, 0.80, 0.66, 0.28, 0.57]
f1_score = [0.84, 0.82, 0.91, 0.80, 0.63, 0.80, 0.66, 0.29, 0.57]

# X positions
x = np.arange(len(labels))
width = 0.2

plt.figure(figsize=(14, 6))

# Bars
bars1 = plt.bar(x - 1.5*width, accuracy, width, label='Accuracy')
bars2 = plt.bar(x - 0.5*width, precision, width, label='Precision')
bars3 = plt.bar(x + 0.5*width, recall, width, label='Recall')
bars4 = plt.bar(x + 1.5*width, f1_score, width, label='F1-Score')

# Add values on top
def add_labels(bars):
    for bar in bars:
        height = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, height + 0.01,
                 f'{height:.2f}', ha='center', fontsize=8)

add_labels(bars1)
add_labels(bars2)
add_labels(bars3)
add_labels(bars4)

# Labels and title
plt.xlabel("Model & Window Size")
plt.ylabel("Score")
plt.title("Performance Comparison Across Window Sizes")
plt.xticks(x, labels, rotation=45)
plt.ylim(0, 1.0)

plt.legend()
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""The results demonstrate on EEG + motion sensor data - a clear impact of window size on model performance, with smaller window sizes yielding significantly better outcomes. Specifically, a window size of 64 achieves the highest accuracy and consistency across all models, particularly with LightGBM performing best overall. As the window size increases to 128 and 256, there is a noticeable decline in performance across all metrics, with the degradation being most severe for SVM. This suggests that smaller windows are more effective in capturing fine-grained temporal patterns in EEG signals, while larger windows may introduce noise or dilute important signal variations. Overall, the findings highlight that optimal window selection is critical for achieving robust and accurate EEG-based classification."""



"""# **for RQ2 n comparison-ML model on only EEG data excluding motion sensor data - for RQ2 - ignoring motion sensor data**

# Here we basically do similar process like above except we will remove features such as motion sensors to check whether it will affect accuracy and in what ways
"""

# ============================================
# 1. IMPORT LIBRARIES
# ============================================
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import matplotlib.pyplot as plt
import seaborn as sns
from lightgbm import LGBMClassifier


# ============================================
# 2. MOUNT GOOGLE DRIVE
# ============================================
from google.colab import drive
drive.mount('/content/drive')

# ============================================
# 3. LOAD MERGED DATASET
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG/merged_EEG_dataset.csv"
df_all = pd.read_csv(data_path)

print("Original shape:", df_all.shape)

# ============================================
# 4. REMOVE MOTION SENSOR COLUMNS
# ============================================



motion_keywords = [
    "MOT.GyroX", "MOT.GyroY", "MOT.GyroZ",
    "MOT.AccX",  "MOT.AccY",  "MOT.AccZ",
    "MOT.MagX",  "MOT.MagY",  "MOT.MagZ"
]

eeg_columns = [col for col in df_all.columns
               if not any(keyword in col for keyword in motion_keywords)]

# Keep EEG + label
df_eeg_only = df_all[eeg_columns]

print("EEG-only shape:", df_eeg_only.shape)

# ============================================
# 5. HANDLE MISSING VALUES
# ============================================
df_eeg_only.fillna(method='ffill', inplace=True)

# ============================================
# 6. NORMALIZATION
# ============================================
features = df_eeg_only.drop("label", axis=1)

scaler = StandardScaler()
scaled_features = scaler.fit_transform(features)

df_scaled = pd.DataFrame(scaled_features, columns=features.columns)
df_scaled["label"] = df_eeg_only["label"].values

# ============================================
# 7. WINDOWING FUNCTION
# ============================================
def create_windows(data, labels, window_size, step_size):
    X = []
    y = []

    for i in range(0, len(data) - window_size, step_size):
        X.append(data[i:i+window_size])
        y.append(labels[i])

    return np.array(X), np.array(y)

window_size = 128
step_size = 64

X, y = create_windows(
    df_scaled.drop("label", axis=1).values,
    df_scaled["label"].values,
    window_size,
    step_size
)

print("Windowed shape:", X.shape)

# ============================================
# 8. LABEL ENCODING
# ============================================
le = LabelEncoder()
y_encoded = le.fit_transform(y)

# ============================================
# 9. TRAIN-TEST SPLIT
# ============================================
X_train, X_test, y_train, y_test = train_test_split(
    X, y_encoded, test_size=0.2, stratify=y_encoded, random_state=42
)

# ============================================
# 10. FLATTEN FOR ML MODELS
# ============================================
X_train_flat = X_train.reshape(X_train.shape[0], -1)
X_test_flat = X_test.reshape(X_test.shape[0], -1)

print("Flattened shape:", X_train_flat.shape)

# ============================================
# 11. TRAIN MODELS
# ============================================

# Random Forest
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train_flat, y_train)

# SVM
svm = SVC(kernel='rbf')
svm.fit(X_train_flat, y_train)

# LightGBM
lgbm1 = LGBMClassifier(
    n_estimators=400,
    learning_rate=0.05,
    max_depth=-1,
    num_leaves=64,
    min_child_samples=10,
    subsample=0.9,
    colsample_bytree=0.9,
    reg_alpha=0.0,
    reg_lambda=0.0,
    n_jobs=-1,
    random_state=42
)
lgbm1.fit(X_train_flat, y_train)

# ============================================
# 11. TRAIN MODELS
# ============================================

# Random Forest
#rf = RandomForestClassifier(n_estimators=100, random_state=42)
#rf.fit(X_train_flat, y_train)

# SVM
#svm = SVC(kernel='rbf')
#svm.fit(X_train_flat, y_train)

# ============================================
# 12. EVALUATION FUNCTION
# ============================================
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)

    print(f"\n===== {name} Results =====")
    print("Accuracy:", accuracy_score(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(y_test, y_pred))

    cm = confusion_matrix(y_test, y_pred)

    plt.figure(figsize=(8,6))
    sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
                xticklabels=le.classes_,
                yticklabels=le.classes_)
    plt.title(f"{name} Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("Actual")
    plt.show()

# ============================================
# 13. EVALUATE
# ============================================
evaluate_model(rf, X_test_flat, y_test, "RF (EEG Only)")
evaluate_model(svm, X_test_flat, y_test, "SVM (EEG Only)")
evaluate_model(lgbm1, X_test_flat, y_test, "LightGBM (EEG Only)")

"""Machine Learning Performance (EEG Only)

Model	Accuracy	Precision (Weighted Avg)	Recall (Weighted Avg)	F1-Score (Weighted Avg)

Random Forest	0.422	0.41	0.42	0.41

SVM	0.308	0.34	0.31	0.31

LightGBM	0.408	0.41	0.41	0.41

# **Diff-Window-sizes-For only EEG data excluding motion sensor data - experiments on different window sizes**
"""

import matplotlib.pyplot as plt
import numpy as np

models = ['Random Forest', 'SVM', 'LightGBM']

accuracy = [0.422, 0.308, 0.408]
precision = [0.41, 0.34, 0.41]
recall = [0.42, 0.31, 0.41]
f1 = [0.41, 0.31, 0.41]

x = np.arange(len(models))
width = 0.2

plt.figure(figsize=(10, 6))

bars1 = plt.bar(x - 1.5*width, accuracy, width, label='Accuracy')
bars2 = plt.bar(x - 0.5*width, precision, width, label='Precision')
bars3 = plt.bar(x + 0.5*width, recall, width, label='Recall')
bars4 = plt.bar(x + 1.5*width, f1, width, label='F1-Score')

# Add values
for bars in [bars1, bars2, bars3, bars4]:
    for bar in bars:
        h = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, h + 0.01, f'{h:.2f}', ha='center', fontsize=8)

plt.xlabel("Models")
plt.ylabel("Score")
plt.title("Machine Learning Performance (EEG Only)")
plt.xticks(x, models)
plt.ylim(0, 1)

plt.legend()
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""The results indicate relatively low performance across all machine learning models when using EEG-only data, suggesting limitations in feature representation. Random Forest and LightGBM exhibit similar performance, slightly outperforming SVM across all evaluation metrics. However, the overall accuracy and F1-scores remain modest, highlighting the challenges of classifying complex EEG signals without additional contextual or multimodal inputs. These findings suggest that EEG-only features may not be sufficiently discriminative for achieving high classification accuracy."""



"""# Here we will conduct experiments on different window size only on EEG data i.e excluding motion sensor features etc - however the process will remain same like above"""

# ============================================
# IMPORTS
# ============================================
import os
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import accuracy_score, classification_report

from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from lightgbm import LGBMClassifier

# ============================================
# FILE PATH
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG/"  # CHANGE THIS

# ============================================
# FILE → LABEL MAP
# ============================================
file_label_map = {
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking",
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "music",
    "Sub1Relax.csv": "relaxed_closed",
    "Sub1Relaxopen.csv": "relaxed_open"
}

# ============================================
# WINDOW FUNCTION
# ============================================
def create_windows(data, window_size, overlap):
    step = int(window_size * (1 - overlap))
    windows = []
    for i in range(0, len(data) - window_size, step):
        windows.append(data[i:i+window_size])
    return np.array(windows)

# ============================================
# BUILD DATASET (EEG ONLY)
# ============================================
def build_dataset_eeg_only(window_size=128, overlap=0.5):

    X_all = []
    y_all = []

    common_cols = None

    # Identify EEG-only columns
    for file in file_label_map:
        df = pd.read_csv(os.path.join(data_path, file))

        # Remove motion columns
        motion_keywords = [ "MOT.GyroX", "MOT.GyroY", "MOT.GyroZ",
              "MOT.AccX",  "MOT.AccY",  "MOT.AccZ",
              "MOT.MagX",  "MOT.MagY",  "MOT.MagZ"]

        df = df[[col for col in df.columns if not any(k in col for k in motion_keywords)]]

        cols = set(df.columns)

        if common_cols is None:
            common_cols = cols
        else:
            common_cols = common_cols.intersection(cols)

    common_cols = sorted(list(common_cols))



    # Build dataset
    for file, label in file_label_map.items():
        df = pd.read_csv(os.path.join(data_path, file))

        # Remove motion columns
        motion_keywords = [
              "MOT.GyroX", "MOT.GyroY", "MOT.GyroZ",
              "MOT.AccX",  "MOT.AccY",  "MOT.AccZ",
              "MOT.MagX",  "MOT.MagY",  "MOT.MagZ"
            ]
        df = df[[col for col in df.columns if not any(k in col for k in motion_keywords)]]

        df = df[common_cols]

        df.fillna(method='ffill', inplace=True)

        scaler = StandardScaler()
        data_scaled = scaler.fit_transform(df)

        windows = create_windows(data_scaled, window_size, overlap)

        labels = [label] * len(windows)

        X_all.append(windows)
        y_all.extend(labels)

    X_all = np.vstack(X_all)
    y_all = np.array(y_all)

    return X_all, y_all

# ============================================
# EVALUATION FUNCTION
# ============================================
def evaluate_model(model, X_test, y_test, name):
    y_pred = model.predict(X_test)

    print(f"\n===== {name} =====")
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))

# ============================================
# MODELS
# ============================================
rf = RandomForestClassifier(n_estimators=150, random_state=42)

svm = SVC(kernel='rbf', C=5, gamma='scale')

lgbm = LGBMClassifier(
    n_estimators=300,
    learning_rate=0.05,
    num_leaves=64,
    random_state=42
)

# ============================================
# WINDOW EXPERIMENT (EEG ONLY)
# ============================================
window_sizes = [64, 128, 256]
overlap = 0.5

le = LabelEncoder()

for w in window_sizes:
    print(f"\n\n========= WINDOW SIZE: {w} =========")

    X, y = build_dataset_eeg_only(window_size=w, overlap=overlap)

    y = le.fit_transform(y)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=42
    )

    # Flatten for ML
    X_train_flat = X_train.reshape(X_train.shape[0], -1)
    X_test_flat = X_test.reshape(X_test.shape[0], -1)

    # Train
    rf.fit(X_train_flat, y_train)
    svm.fit(X_train_flat, y_train)
    lgbm.fit(X_train_flat, y_train)

    # Evaluate
    evaluate_model(rf, X_test_flat, y_test, f"RF EEG Only (W={w})")
    evaluate_model(svm, X_test_flat, y_test, f"SVM EEG Only (W={w})")
    evaluate_model(lgbm, X_test_flat, y_test, f"LightGBM EEG Only (W={w})")

"""EEG-Only Performance Across Window Sizes

Window Size	Model	Accuracy	Precision (Weighted)	Recall (Weighted)	F1-Score (Weighted)

64	Random Forest	0.597	0.61	0.60	0.59

	SVM	0.535	0.56	0.53	0.54
	LightGBM	0.597	0.60	0.60	0.60
128	Random Forest	0.404	0.40	0.40	0.39

	SVM	0.361	0.40	0.36	0.35
	LightGBM	0.394	0.39	0.39	0.39
256	Random Forest	0.333	0.38	0.33	0.33

	SVM	0.225	0.24	0.23	0.22
	LightGBM	0.225	0.20	0.23	0.21
"""

import matplotlib.pyplot as plt
import numpy as np

labels = [
    'RF-64', 'SVM-64', 'LGBM-64',
    'RF-128', 'SVM-128', 'LGBM-128',
    'RF-256', 'SVM-256', 'LGBM-256'
]

accuracy = [0.597, 0.535, 0.597, 0.404, 0.361, 0.394, 0.333, 0.225, 0.225]
precision = [0.61, 0.56, 0.60, 0.40, 0.40, 0.39, 0.38, 0.24, 0.20]
recall = [0.60, 0.53, 0.60, 0.40, 0.36, 0.39, 0.33, 0.23, 0.23]
f1 = [0.59, 0.54, 0.60, 0.39, 0.35, 0.39, 0.33, 0.22, 0.21]

x = np.arange(len(labels))
width = 0.2

plt.figure(figsize=(14, 6))

bars1 = plt.bar(x - 1.5*width, accuracy, width, label='Accuracy')
bars2 = plt.bar(x - 0.5*width, precision, width, label='Precision')
bars3 = plt.bar(x + 0.5*width, recall, width, label='Recall')
bars4 = plt.bar(x + 1.5*width, f1, width, label='F1-Score')

# Add values
for bars in [bars1, bars2, bars3, bars4]:
    for bar in bars:
        h = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, h + 0.01, f'{h:.2f}', ha='center', fontsize=7)

plt.xlabel("Model & Window Size")
plt.ylabel("Score")
plt.title("EEG-Only Performance Across Window Sizes")
plt.xticks(x, labels, rotation=45)
plt.ylim(0, 1)

plt.legend()
plt.grid(axis='y')
plt.tight_layout()
plt.show()

"""The analysis across different window sizes reveals that smaller windows (64) consistently achieve better performance compared to larger window sizes. As the window size increases to 128 and 256, there is a significant decline in accuracy and other evaluation metrics across all models, with SVM showing the most pronounced degradation. This trend indicates that smaller window sizes are more effective in capturing short-term temporal variations in EEG signals, whereas larger windows may smooth out critical patterns and introduce noise. Overall, the findings reinforce the importance of optimal window selection in improving EEG-based classification performance."""



"""# **RQ3 - deep learning models(CNN, LSTM) EEG n EEG+motion sensors data**

# Here we will train DL models - here we can use raw data - without flattening

# basically we will train DL models on both - EEG only data and EEG + motion sensors data
"""

# ============================================
# 1. IMPORTS
# ============================================
import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, LSTM
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import to_categorical   # ✅ IMPORTANT

# ============================================
# 2. DATA PATH
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG"

# ============================================
# 3. FILE → LABEL MAP
# ============================================
file_label_map = {
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "music",
    "Sub1Relax.csv": "relax_closed",
    "Sub1Relaxopen.csv": "relax_open",
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking"
}

# ============================================
# 4. WINDOW FUNCTION
# ============================================
def create_windows(data, window_size=128, step=64):
    windows = []
    for i in range(0, len(data) - window_size, step):
        windows.append(data[i:i+window_size])
    return np.array(windows)

# ============================================
# 5. BUILD DATASET
# ============================================
def build_dataset(use_eeg_only=False):

    X_all = []
    y_all = []

    for file, label in file_label_map.items():
        df = pd.read_csv(os.path.join(data_path, file))
        df.columns = [c.strip() for c in df.columns]
        df.fillna(method='ffill', inplace=True)

        # Remove motion
        if use_eeg_only:
            motion_keywords = [
                "MOT.GyroX","MOT.GyroY","MOT.GyroZ",
                "MOT.AccX","MOT.AccY","MOT.AccZ",
                "MOT.MagX","MOT.MagY","MOT.MagZ","EEG.RawCq"
            ]
            df = df[[col for col in df.columns if not any(k in col for k in motion_keywords)]]

        scaler = StandardScaler()
        data_scaled = scaler.fit_transform(df)

        windows = create_windows(data_scaled)

        labels = [label] * len(windows)

        X_all.append(windows)
        y_all.extend(labels)

    X_all = np.vstack(X_all)
    y_all = np.array(y_all)

    return X_all, y_all

# ============================================
# 6. PREPARE DATA
# ============================================
def prepare_data(use_eeg_only=False):

    X, y = build_dataset(use_eeg_only)

    le = LabelEncoder()
    y_encoded = le.fit_transform(y)

    num_classes = len(np.unique(y_encoded))
    y_cat = to_categorical(y_encoded, num_classes=num_classes)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_cat,
        test_size=0.2,
        stratify=y_encoded,
        random_state=42
    )

    return X_train, X_test, y_train, y_test, le, num_classes

# ============================================
# 7. MODELS
# ============================================
def build_cnn(input_shape, num_classes):
    model = Sequential([
        Conv1D(64, 5, activation='relu', input_shape=input_shape),
        MaxPooling1D(2),
        Conv1D(128, 5, activation='relu'),
        MaxPooling1D(2),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


def build_lstm(input_shape, num_classes):
    model = Sequential([
        LSTM(128, return_sequences=True, input_shape=input_shape),
        Dropout(0.3),

        LSTM(64),
        Dropout(0.3),

        Dense(64, activation='relu'),
        Dropout(0.4),

        Dense(num_classes, activation='softmax')
    ])

    model.compile(
        optimizer='adam',
        loss='categorical_crossentropy',
        metrics=['accuracy']
    )

    return model

# ============================================
# 8. TRAIN + EVALUATE
# ============================================
def run_experiment(use_eeg_only=False, name=""):

    X_train, X_test, y_train, y_test, le, num_classes = prepare_data(use_eeg_only)

    input_shape = (X_train.shape[1], X_train.shape[2])

    early = EarlyStopping(patience=3, restore_best_weights=True)

    # CNN
    cnn = build_cnn(input_shape, num_classes)
    cnn.fit(X_train, y_train,
            epochs=20,
            batch_size=32,
            validation_split=0.2,
            callbacks=[early],
            verbose=1)

    # LSTM
    lstm = build_lstm(input_shape, num_classes)
    lstm.fit(X_train, y_train,
             epochs=20,
             batch_size=32,
             validation_split=0.2,
             callbacks=[early],
             verbose=1)

    for model, mname in [(cnn, "CNN"), (lstm, "LSTM")]:
        y_pred = np.argmax(model.predict(X_test), axis=1)
        y_true = np.argmax(y_test, axis=1)

        print(f"\n==== {mname} ({name}) ====")
        print("Accuracy:", accuracy_score(y_true, y_pred))
        print(classification_report(y_true, y_pred))

        cm = confusion_matrix(y_true, y_pred)

        plt.figure(figsize=(6,5))
        sns.heatmap(cm, annot=True, fmt='d',
                    xticklabels=le.classes_,
                    yticklabels=le.classes_)
        plt.title(f"{mname} - {name}")
        plt.xlabel("Predicted")
        plt.ylabel("Actual")
        plt.show()

# ============================================
# 9. RUN
# ============================================
run_experiment(use_eeg_only=False, name="EEG + Motion")
run_experiment(use_eeg_only=True, name="EEG Only")

"""Data Type	Model	Accuracy	Precision (Weighted Avg)	Recall (Weighted Avg)	F1-Score (Weighted Avg)

EEG + Motion	- CNN	0.78	0.79	0.78	0.78

EEG + Motion	- LSTM	0.16	0.17	0.16	0.15

EEG Only	- CNN	0.53	0.55	0.53	0.53

EEG Only	- LSTM	0.19	0.14	0.19	0.12
"""

import matplotlib.pyplot as plt
import numpy as np

models = ['CNN (EEG+Motion)', 'LSTM (EEG+Motion)', 'CNN (EEG)', 'LSTM (EEG)']

accuracy = [0.78, 0.16, 0.53, 0.19]
precision = [0.79, 0.17, 0.55, 0.14]
recall = [0.78, 0.16, 0.53, 0.19]
f1 = [0.78, 0.15, 0.53, 0.12]

x = np.arange(len(models))
width = 0.2

plt.figure(figsize=(12,6))

bars1 = plt.bar(x - 1.5*width, accuracy, width, label='Accuracy')
bars2 = plt.bar(x - 0.5*width, precision, width, label='Precision')
bars3 = plt.bar(x + 0.5*width, recall, width, label='Recall')
bars4 = plt.bar(x + 1.5*width, f1, width, label='F1-Score')

# Value labels
for bars in [bars1, bars2, bars3, bars4]:
    for bar in bars:
        h = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, h + 0.01, f'{h:.2f}', ha='center', fontsize=8)

plt.xticks(x, models, rotation=30)
plt.ylim(0,1)
plt.xlabel("Model Type")
plt.ylabel("Score")
plt.title("Deep Learning Performance (EEG vs EEG+Motion)")
plt.legend()
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""The results clearly demonstrate that CNN significantly outperforms LSTM across both EEG-only and multimodal (EEG + Motion) data. The CNN model achieves the highest performance when using combined EEG and motion sensor inputs, highlighting the effectiveness of multimodal data fusion. In contrast, LSTM exhibits extremely low performance in both cases, suggesting its limitations in learning meaningful temporal dependencies from the given dataset. Overall, CNN proves to be more robust and suitable for this classification task, particularly when enriched with additional sensor data."""



"""# **Experiments run on diff Window sizes DL for EEG + motion sensor data & comparison table**"""

# ============================================
# IMPORTS
# ============================================
import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, LSTM, Dropout
from tensorflow.keras.utils import to_categorical

# ============================================
# FILE PATH
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG"  # CHANGE THIS

# ============================================
# FILE → LABEL MAP
# ============================================
file_label_map = {
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking",
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "music",
    "Sub1Relax.csv": "relaxed_closed",
    "Sub1Relaxopen.csv": "relaxed_open"
}

# ============================================
# WINDOW FUNCTION
# ============================================
def create_windows(data, window_size=128, overlap=0.5):
    step = int(window_size * (1 - overlap))  #

    windows = []
    for i in range(0, len(data) - window_size, step):
        windows.append(data[i:i+window_size])

    return np.array(windows)

# ============================================
# BUILD DATASET (EEG + MOTION)
# ============================================
def build_dataset(window_size=128, overlap=0.5):

    X_all = []
    y_all = []


    common_cols = None
    for file in file_label_map:
        df = pd.read_csv(os.path.join(data_path, file))
        cols = set(df.columns)

        if common_cols is None:
            common_cols = cols
        else:
            common_cols = common_cols.intersection(cols)

    common_cols = sorted(list(common_cols))

    # Build dataset
    for file, label in file_label_map.items():
        df = pd.read_csv(os.path.join(data_path, file))
        df = df[common_cols]

        df.fillna(method='ffill', inplace=True)

        scaler = StandardScaler()
        data_scaled = scaler.fit_transform(df)

        # ✅ windowing
        windows = create_windows(data_scaled, window_size, overlap)

        labels = [label] * len(windows)

        X_all.append(windows)
        y_all.extend(labels)

    X_all = np.vstack(X_all)
    y_all = np.array(y_all)

    return X_all, y_all

# ============================================
# CNN MODEL
# ============================================
def build_cnn(input_shape, num_classes):
    model = Sequential([
        Conv1D(64, 3, activation='relu', input_shape=input_shape),
        MaxPooling1D(2),
        Conv1D(128, 3, activation='relu'),
        MaxPooling1D(2),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# ============================================
# LSTM MODEL
# ============================================
def build_lstm(input_shape, num_classes):
    model = Sequential([
        LSTM(128, input_shape=input_shape),
        Dropout(0.5),
        Dense(64, activation='relu'),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# ============================================
# MAIN EXPERIMENT LOOP as 128 is already done
# ============================================
window_sizes = [64, 128, 256]
overlap = 0.5

le = LabelEncoder()

for w in window_sizes:
    print(f"\n\n========= WINDOW SIZE: {w} =========")

    # Load dataset
    X, y = build_dataset(window_size=w, overlap=overlap)

    # Encode labels
    y_encoded = le.fit_transform(y)
    y_cat = to_categorical(y_encoded)

    # Train-test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y_cat, test_size=0.2, stratify=y_encoded, random_state=42
    )

    #  dtype (important for DL)
    X_train = X_train.astype(np.float32)
    X_test = X_test.astype(np.float32)

    input_shape = (X_train.shape[1], X_train.shape[2])
    num_classes = y_cat.shape[1]

    # =====================================
    # CNN
    # =====================================
    cnn = build_cnn(input_shape, num_classes)

    cnn.fit(X_train, y_train,
            epochs=15,
            batch_size=32,
            validation_split=0.2,
            verbose=0)

    y_pred_cnn = np.argmax(cnn.predict(X_test), axis=1)
    y_true = np.argmax(y_test, axis=1)

    print("\n==== CNN Results ====")
    print("Accuracy:", accuracy_score(y_true, y_pred_cnn))

    # =====================================
    # LSTM
    # =====================================
    lstm = build_lstm(input_shape, num_classes)

    lstm.fit(X_train, y_train,
             epochs=15,
             batch_size=32,
             validation_split=0.2,
             verbose=0)

    y_pred_lstm = np.argmax(lstm.predict(X_test), axis=1)

    print("\n==== LSTM Results ====")
    print("Accuracy:", accuracy_score(y_true, y_pred_lstm))

"""*📊 Deep Learning Results (EEG + Motion Sensors)

Window Size	CNN Accuracy	LSTM Accuracy

64	0.8926	0.7685

128	0.8173	0.4856

256	0.6863	0.2157*



"""

import matplotlib.pyplot as plt
import numpy as np

windows = ['64', '128', '256']

cnn = [0.8926, 0.8173, 0.6863]
lstm = [0.7685, 0.4856, 0.2157]

x = np.arange(len(windows))
width = 0.3

plt.figure(figsize=(10,6))

bars1 = plt.bar(x - width/2, cnn, width, label='CNN')
bars2 = plt.bar(x + width/2, lstm, width, label='LSTM')

# Labels
for bars in [bars1, bars2]:
    for bar in bars:
        h = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, h + 0.01, f'{h:.2f}', ha='center', fontsize=9)

plt.xticks(x, windows)
plt.xlabel("Window Size")
plt.ylabel("Accuracy")
plt.title("Deep Learning Performance (EEG + Motion)")
plt.ylim(0,1)

plt.legend()
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""The results indicate that smaller window sizes (64) yield the highest accuracy for both CNN and LSTM models when using EEG combined with motion sensor data. As the window size increases, performance declines steadily, with LSTM showing a sharp drop at larger window sizes. CNN maintains relatively strong performance across all windows but still experiences degradation. These findings suggest that shorter temporal windows are more effective in capturing meaningful patterns, while larger windows may dilute critical signal variations, particularly affecting sequence-based models like LSTM.

# **Experiments run on diff Window sizes DL for only EEG data without motion sensor data & comparison table**
"""

# ============================================
# IMPORTS
# ============================================
import os
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, LSTM, Dropout
from tensorflow.keras.utils import to_categorical

# ============================================
# FILE PATH
# ============================================
data_path = "/content/drive/MyDrive/sajid_EEG_project/updated_csv_data_EEG"  # CHANGE THIS

# ============================================
# FILE → LABEL MAP
# ============================================
file_label_map = {
    "Sub1SUSD.csv": "sit_stand",
    "Sub1Talking.csv": "talking",
    "Sub1Walking.csv": "walking",
    "Sub1EB.csv": "eye_blink",
    "Sub1EBM.csv": "eyebrow",
    "Sub1EM.csv": "eye_movement",
    "Sub1HS.csv": "head_shake",
    "Sub1HT.csv": "head_nod",
    "Sub1LS.csv": "leg_shake",
    "Sub1Music.csv": "music",
    "Sub1Relax.csv": "relaxed_closed",
    "Sub1Relaxopen.csv": "relaxed_open"
}

# ============================================
# WINDOW FUNCTION
# ============================================
def create_windows(data, window_size=128, overlap=0.5):
    step = int(window_size * (1 - overlap))
    windows = []
    for i in range(0, len(data) - window_size, step):
        windows.append(data[i:i+window_size])
    return np.array(windows)

# ============================================
# BUILD DATASET (EEG ONLY)
# ============================================
def build_dataset_eeg_only(window_size=128, overlap=0.5):

    X_all = []
    y_all = []

    common_cols = None

    # EEG-only columns
    for file in file_label_map:
        df = pd.read_csv(os.path.join(data_path, file))

        # Remove motion sensor columns
        motion_keywords = [
              "MOT.GyroX", "MOT.GyroY", "MOT.GyroZ",
              "MOT.AccX",  "MOT.AccY",  "MOT.AccZ",
              "MOT.MagX",  "MOT.MagY",  "MOT.MagZ"
            ]
        df = df[[col for col in df.columns if not any(k in col for k in motion_keywords)]]

        cols = set(df.columns)

        if common_cols is None:
            common_cols = cols
        else:
            common_cols = common_cols.intersection(cols)

    common_cols = sorted(list(common_cols))

    # Build dataset
    for file, label in file_label_map.items():
        df = pd.read_csv(os.path.join(data_path, file))

        # Remove motion sensor columns
        motion_keywords = [
              "MOT.GyroX", "MOT.GyroY", "MOT.GyroZ",
              "MOT.AccX",  "MOT.AccY",  "MOT.AccZ",
              "MOT.MagX",  "MOT.MagY",  "MOT.MagZ"
            ]
        df = df[[col for col in df.columns if not any(k in col for k in motion_keywords)]]

        df = df[common_cols]

        #
        df.ffill(inplace=True)

        scaler = StandardScaler()
        data_scaled = scaler.fit_transform(df)

        windows = create_windows(data_scaled, window_size, overlap)

        labels = [label] * len(windows)

        X_all.append(windows)
        y_all.extend(labels)

    X_all = np.vstack(X_all)
    y_all = np.array(y_all)

    return X_all, y_all

# ============================================
# CNN MODEL
# ============================================
def build_cnn(input_shape, num_classes):
    model = Sequential([
        Conv1D(64, 3, activation='relu', input_shape=input_shape),
        MaxPooling1D(2),
        Conv1D(128, 3, activation='relu'),
        MaxPooling1D(2),
        Flatten(),
        Dense(128, activation='relu'),
        Dropout(0.5),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# ============================================
# LSTM MODEL
# ============================================
def build_lstm(input_shape, num_classes):
    model = Sequential([
        LSTM(128, input_shape=input_shape),
        Dropout(0.5),
        Dense(64, activation='relu'),
        Dense(num_classes, activation='softmax')
    ])
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

# ============================================
# MAIN EXPERIMENT LOOP
# ============================================
window_sizes = [64, 128, 256]
overlap = 0.5

le = LabelEncoder()

for w in window_sizes:
    print(f"\n\n========= WINDOW SIZE: {w} =========")

    X, y = build_dataset_eeg_only(window_size=w, overlap=overlap)

    y_encoded = le.fit_transform(y)
    y_cat = to_categorical(y_encoded)

    X_train, X_test, y_train, y_test = train_test_split(
        X, y_cat, test_size=0.2, stratify=y_encoded, random_state=42
    )

    #  dtype
    X_train = X_train.astype(np.float32)
    X_test = X_test.astype(np.float32)

    input_shape = (X_train.shape[1], X_train.shape[2])
    num_classes = y_cat.shape[1]

    # =====================================
    # CNN
    # =====================================
    cnn = build_cnn(input_shape, num_classes)

    cnn.fit(X_train, y_train,
            epochs=15,
            batch_size=32,
            validation_split=0.2,
            verbose=0)

    y_pred_cnn = np.argmax(cnn.predict(X_test), axis=1)
    y_true = np.argmax(y_test, axis=1)

    print("\n==== CNN (EEG ONLY) ====")
    print("Accuracy:", accuracy_score(y_true, y_pred_cnn))

    # =====================================
    # LSTM
    # =====================================
    lstm = build_lstm(input_shape, num_classes)

    lstm.fit(X_train, y_train,
             epochs=15,
             batch_size=32,
             validation_split=0.2,
             verbose=0)

    y_pred_lstm = np.argmax(lstm.predict(X_test), axis=1)

    print("\n==== LSTM (EEG ONLY) ====")
    print("Accuracy:", accuracy_score(y_true, y_pred_lstm))

"""Deep Learning Results (EEG Only)

Window Size	CNN Accuracy	LSTM Accuracy

64           	0.7041	0.5298

128          	0.5625	0.3654

256          	0.4804	0.2255
"""

import matplotlib.pyplot as plt
import numpy as np

windows = ['64', '128', '256']

cnn = [0.7041, 0.5625, 0.4804]
lstm = [0.5298, 0.3654, 0.2255]

x = np.arange(len(windows))
width = 0.3

plt.figure(figsize=(10,6))

bars1 = plt.bar(x - width/2, cnn, width, label='CNN')
bars2 = plt.bar(x + width/2, lstm, width, label='LSTM')

# Labels
for bars in [bars1, bars2]:
    for bar in bars:
        h = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, h + 0.01, f'{h:.2f}', ha='center', fontsize=9)

plt.xticks(x, windows)
plt.xlabel("Window Size")
plt.ylabel("Accuracy")
plt.title("Deep Learning Performance (EEG Only)")
plt.ylim(0,1)

plt.legend()
plt.grid(axis='y')

plt.tight_layout()
plt.show()

"""The EEG-only results follow a similar trend, where smaller window sizes (64) achieve the best performance for both CNN and LSTM models. However, overall accuracy is lower compared to the multimodal setup, indicating the limitations of relying solely on EEG data. CNN continues to outperform LSTM across all window sizes, demonstrating its superior ability to capture spatial patterns in EEG signals. The performance degradation at larger window sizes further reinforces the importance of selecting an optimal window size for effective EEG-based classification."""





